### ISSUE TITLE
cancel link not showing

### ISSUE THREAD

**Issue by wdfee** [WPManageNinja/WooCommerce-Order-Cancel-for-Customers#1]
Hello, with WP 4.9.1, and newest WooCommerce 3.2.5, the cancel link doesn't show up on customer's order page. (tested with TwentySeventeen, new plugin installation, didn't test before)

**Comment by techjewel** [comment]
Hi @wdfee Thanks for open the bug. I will take a look and commit a fix.

Thanks

**Comment by wdfee** [comment]
wow, whar a quick answer! wait, quite at the moment I figured out, this issue appears if nothing is set in setting "Threshold Time for Cancel order ( in minutes )" - I wanted to let the cancellation time open. With a big number in it, it works. So this isn't actually a bug, sorry.
But maybe a feature request to allow cancellations forever...

**Comment by techjewel** [comment]
Good to know. If you want would like to request a feature please open a new issue. I am closing this issue now.

Thanks

**Comment by kirpi-it** [comment]
Yet it is quite funny: if you set a time up to 67 minutes the link does not show. 
From 68 on, it shows...
I do not know if this is a real bug or not, but it could be an issue in some cases. For instance, we sell food and deliver in our area in 20-40 minutes time. While we are happy to agree cancellations just after the order (anybody might place a wrong order after all), we should keep the cancellation time in the range of 10-15 minutes after the order. After that the food goes into production.
Quite strange this 68 minutes threshold.
What do you think?
Thank you!
