### ISSUE TITLE
ERROR - White Page Redirect

### ISSUE THREAD

**Issue by MissCharmaine** [WPManageNinja/WooCommerce-Order-Cancel-for-Customers#4]
Hey, I am using this plugin on a local wordpress site I am currently updating. 

When a "customer" cancels an order they are redirected to a white page with the admin email address displayed. 

No email gets sent to the admin but the order status changes within the Woocommerce dashboard.

Is this an error because I am working on a local site? I am not too familiar with editing plugins but if you give me a code to fix this I can give it a go.

Thanks

**Comment by techjewel** [comment]
After Cancel user will by default redirect to account orders page. Make sure your woocommerce have configured for account dashboard. You can also filter the after cancel redirect url by hooking `wco_after_cancel_redirect_url` filter.
