### ISSUE TITLE
Cancel Order Error

### ISSUE THREAD

**Issue by SkyRanger** [WPManageNinja/WooCommerce-Order-Cancel-for-Customers#7]
> Warning: Cannot modify header information – headers already sent by (output started at /home3/keytags/public_html/wp-content/plugins/woo-order-cancel-for-customers/woocommerce-order-cancel.php:259) in /home3/keytags/public_html/wp-includes/pluggable.php on line 1216

**Comment by techjewel** [comment]
Thanks for reporting. I will take a look.

**Comment by techjewel** [comment]
Hello @SkyRanger 
I have fixed the issue and pushed the updates to WordPress Plugin repository. Please upgrade your version to 1.1

https://wordpress.org/plugins/woo-order-cancel-for-customers/advanced/

Thanks

**Comment by SkyRanger** [comment]
Awesome it works.  Thank you for the quick fix. Will be purchasing the pro version shortly.
